# MATIAS HERTER 
# 101272358



In [1]:
import pandas as pd

1 - Download the test.csv file and store it in a DataFrame named, myDF

In [2]:
myDF = pd.read_csv('test.csv')

2 - Show the first five rows of the DF.

In [3]:
myDF.head()

Matias Herter   Unnamed: 1  Unnamed: 2 Unnamed: 3 Unnamed: 4
0      101272358         NaN         NaN        NaN        NaN
1             10       192.0        50.0          F     NXEYEM
2             20       299.0        21.0          M     VNFKZD
3             30       378.0        28.0          X     IMGMFY
4             40       156.0        44.0          Q     RHRHJY

3 - Does the first row contain the column names? If not, please assign the following column names to
them:
[ID, Range, Value, Machine Type, Zip code]

In [4]:
myColumsn = ['ID','Range','Value','Machine Type','Zip code']
myDF = pd.read_csv('test.csv', header = None, names = myColumsn)
myDF.head()

ID  Range  Value Machine Type Zip code
0  Matias Herter     NaN    NaN          NaN      NaN
1       101272358    NaN    NaN          NaN      NaN
2              10  192.0   50.0            F   NXEYEM
3              20  299.0   21.0            M   VNFKZD
4              30  378.0   28.0            X   IMGMFY

4 - Add your name and student number on top of your dataset in your local file and show your DF
with your name and student number as part of the dataset.

In [5]:
myDF.head()

ID  Range  Value Machine Type Zip code
0  Matias Herter     NaN    NaN          NaN      NaN
1       101272358    NaN    NaN          NaN      NaN
2              10  192.0   50.0            F   NXEYEM
3              20  299.0   21.0            M   VNFKZD
4              30  378.0   28.0            X   IMGMFY

5 - Now, use a method to skip the first row and show the DF as it was before adding your information

In [6]:
myDF = pd.read_csv('test.csv', header = None, names = myColumsn, skiprows=2)

In [7]:
myDF.head()

ID  Range  Value Machine Type Zip code
0  10  192.0   50.0            F   NXEYEM
1  20  299.0   21.0            M   VNFKZD
2  30  378.0   28.0            X   IMGMFY
3  40  156.0   44.0            Q   RHRHJY
4  50  468.0   33.0            J   HPQCMC

6 - Show the type of your DF

In [8]:
type(myDF)

pandas.core.frame.DataFrame

7 - Select the ‘Value’ column using two different commands. Which one is more object-oriented
style?


*** Simpler Way ***


In [9]:
myDF.Value

0      50.0
1      21.0
2      28.0
3      44.0
4      33.0
       ... 
946    12.0
947    46.0
948    46.0
949    13.0
950    10.0
Name: Value, Length: 951, dtype: float64

*** More Object Oriented Way ***

In [10]:
myDF['Value']

0      50.0
1      21.0
2      28.0
3      44.0
4      33.0
       ... 
946    12.0
947    46.0
948    46.0
949    13.0
950    10.0
Name: Value, Length: 951, dtype: float64

8 - What is the type of this selected column?

In [11]:
myDF['Value'].dtype

dtype('float64')

9 - Can we apply both methods (mentioned in question 7) for fetching the ‘Zip code’ column? Which
other column has the same status? Why we cannot use both method for fetching its content? 

In [12]:
myDF.Zip code #Does not work due to the space between words. Thats why we SHOULD NOT use variable.columnName on our codes

SyntaxError: ignored

In [13]:
myDF['Zip code'].head()

0    NXEYEM
1    VNFKZD
2    IMGMFY
3    RHRHJY
4    HPQCMC
Name: Zip code, dtype: object

10 - . Create a new Series called ‘Brand’ by combining 'Machine Type' and 'Zip code' Series.

In [14]:
myDF['Brand'] = myDF['Machine Type'] + ',' + myDF['Zip code']

In [15]:
myDF.head()

ID  Range  Value Machine Type Zip code     Brand
0  10  192.0   50.0            F   NXEYEM  F,NXEYEM
1  20  299.0   21.0            M   VNFKZD  M,VNFKZD
2  30  378.0   28.0            X   IMGMFY  X,IMGMFY
3  40  156.0   44.0            Q   RHRHJY  Q,RHRHJY
4  50  468.0   33.0            J   HPQCMC  J,HPQCMC

11 - Create a new Series called ‘Total’ by multiplying ‘Range’ and ‘Value’ Series.

In [16]:
myDF['Total'] = (myDF['Range'] * myDF['Value'])
myDF.head()

ID  Range  Value Machine Type Zip code     Brand    Total
0  10  192.0   50.0            F   NXEYEM  F,NXEYEM   9600.0
1  20  299.0   21.0            M   VNFKZD  M,VNFKZD   6279.0
2  30  378.0   28.0            X   IMGMFY  X,IMGMFY  10584.0
3  40  156.0   44.0            Q   RHRHJY  Q,RHRHJY   6864.0
4  50  468.0   33.0            J   HPQCMC  J,HPQCMC  15444.0

12 - Use the following commands:
a. myDF.head()
b. myDF.describe()
c. myDF.describe
d. myDF.shape
e. myDF.dtypes
Why some have parentheses and some don’t? What is the difference between b. and c.?

# () Methods/Actions
# . Attribute 


In [17]:
myDF.head()

ID  Range  Value Machine Type Zip code     Brand    Total
0  10  192.0   50.0            F   NXEYEM  F,NXEYEM   9600.0
1  20  299.0   21.0            M   VNFKZD  M,VNFKZD   6279.0
2  30  378.0   28.0            X   IMGMFY  X,IMGMFY  10584.0
3  40  156.0   44.0            Q   RHRHJY  Q,RHRHJY   6864.0
4  50  468.0   33.0            J   HPQCMC  J,HPQCMC  15444.0

In [18]:
myDF.describe() #SHOWS DATA IN TABLE

Range       Value         Total
count  950.000000  950.000000    950.000000
mean   297.437895   29.943158   8965.992632
std    115.828540   12.267347   5261.283254
min    100.000000   10.000000   1090.000000
25%    194.000000   19.000000   4864.750000
50%    296.000000   30.000000   7916.000000
75%    398.750000   41.000000  12367.750000
max    500.000000   50.000000  24750.000000

In [19]:
myDF.describe #DISPLAYS DATA IN PLAIN TEXT WITH NO DATA TREATMENT

<bound method NDFrame.describe of        ID  Range  Value Machine Type Zip code     Brand    Total
0      10  192.0   50.0            F   NXEYEM  F,NXEYEM   9600.0
1      20  299.0   21.0            M   VNFKZD  M,VNFKZD   6279.0
2      30  378.0   28.0            X   IMGMFY  X,IMGMFY  10584.0
3      40  156.0   44.0            Q   RHRHJY  Q,RHRHJY   6864.0
4      50  468.0   33.0            J   HPQCMC  J,HPQCMC  15444.0
..    ...    ...    ...          ...      ...       ...      ...
946  9460  136.0   12.0            C   HGVBPV  C,HGVBPV   1632.0
947  9470  316.0   46.0            L   SHBAUD  L,SHBAUD  14536.0
948  9480  461.0   46.0            K   PUZUVO  K,PUZUVO  21206.0
949  9490  185.0   13.0            N   UMESZO  N,UMESZO   2405.0
950  9500  137.0   10.0            W   JOHHVL  W,JOHHVL   1370.0

[951 rows x 7 columns]>

In [20]:
myDF.shape #Rows and Columsn

(951, 7)

In [21]:
myDF.dtypes #Data type of columns

ID               object
Range           float64
Value           float64
Machine Type     object
Zip code         object
Brand            object
Total           float64
dtype: object

13 - How can we use the describe() method to show the statistics for the object (not numerical)
columns?


In [22]:
myDF.describe(include='object')

ID Machine Type Zip code     Brand
count    951          948      941       939
unique   951           26      941       939
top     2770            F   TPFEWI  N,REHMAM
freq       1           50        1         1

14 - Rename the ‘ID’ to ‘My ID’ in the DF without replacing the ID Series name in the original DF.
Show the unchanged DF by displaying the top 5 rows.

In [23]:
newMyDF = myDF.rename(columns={'ID':'My ID'})

In [24]:
myDF.head()

ID  Range  Value Machine Type Zip code     Brand    Total
0  10  192.0   50.0            F   NXEYEM  F,NXEYEM   9600.0
1  20  299.0   21.0            M   VNFKZD  M,VNFKZD   6279.0
2  30  378.0   28.0            X   IMGMFY  X,IMGMFY  10584.0
3  40  156.0   44.0            Q   RHRHJY  Q,RHRHJY   6864.0
4  50  468.0   33.0            J   HPQCMC  J,HPQCMC  15444.0

In [25]:
newMyDF.head()

My ID  Range  Value Machine Type Zip code     Brand    Total
0    10  192.0   50.0            F   NXEYEM  F,NXEYEM   9600.0
1    20  299.0   21.0            M   VNFKZD  M,VNFKZD   6279.0
2    30  378.0   28.0            X   IMGMFY  X,IMGMFY  10584.0
3    40  156.0   44.0            Q   RHRHJY  Q,RHRHJY   6864.0
4    50  468.0   33.0            J   HPQCMC  J,HPQCMC  15444.0

15 - Rename the ‘ID’ to ‘My ID’ inplace and show the changed column name using the head()
method.

In [26]:
myDF.rename(columns={'ID':'My ID'}, inplace=True)

16 - Show the DF columns. 


In [27]:
myDF.head()


My ID  Range  Value Machine Type Zip code     Brand    Total
0    10  192.0   50.0            F   NXEYEM  F,NXEYEM   9600.0
1    20  299.0   21.0            M   VNFKZD  M,VNFKZD   6279.0
2    30  378.0   28.0            X   IMGMFY  X,IMGMFY  10584.0
3    40  156.0   44.0            Q   RHRHJY  Q,RHRHJY   6864.0
4    50  468.0   33.0            J   HPQCMC  J,HPQCMC  15444.0

17 - Change all the column names to ['id', 'range', 'value', 'machine type', 'zip code', 'brand', 'total'] and
display the new column names.

In [28]:
myColumsn = ['id', 'range', 'value', 'machine type', 'zip code', 'brand', 'total']

In [29]:
myDF.columns = myColumsn

In [30]:
myDF.head()

id  range  value machine type zip code     brand    total
0  10  192.0   50.0            F   NXEYEM  F,NXEYEM   9600.0
1  20  299.0   21.0            M   VNFKZD  M,VNFKZD   6279.0
2  30  378.0   28.0            X   IMGMFY  X,IMGMFY  10584.0
3  40  156.0   44.0            Q   RHRHJY  Q,RHRHJY   6864.0
4  50  468.0   33.0            J   HPQCMC  J,HPQCMC  15444.0

18 - Replace all the spaces in the column names with ‘_’ and show the changed column again.



In [31]:
myDF.columns = myDF.columns.str.replace(' ', '_')
myDF.head()


id  range  value machine_type zip_code     brand    total
0  10  192.0   50.0            F   NXEYEM  F,NXEYEM   9600.0
1  20  299.0   21.0            M   VNFKZD  M,VNFKZD   6279.0
2  30  378.0   28.0            X   IMGMFY  X,IMGMFY  10584.0
3  40  156.0   44.0            Q   RHRHJY  Q,RHRHJY   6864.0
4  50  468.0   33.0            J   HPQCMC  J,HPQCMC  15444.0

19 - Delete the 'brand', 'total' columns permanently. 

In [32]:
myDF.drop(['brand','total'], axis=1, inplace=True)

20 - Delete row number 3 and row number 5 from the DF permanently and show the top 5 rows.

In [33]:
myDF.drop([3,5],axis=0,inplace=True)

In [35]:
myDF.head()

id  range  value machine_type zip_code
0  10  192.0   50.0            F   NXEYEM
1  20  299.0   21.0            M   VNFKZD
2  30  378.0   28.0            X   IMGMFY
4  50  468.0   33.0            J   HPQCMC
6  70  327.0   24.0            F   NLVQPY

21 - Sort the value Series in ascending order, showing only the value column.

In [36]:
myDF.sort_values('value') #Ascending is the standart 

id  range  value machine_type zip_code
950                          9500  137.0   10.0            W   JOHHVL
506                          5070  268.0   10.0            N   WHIZNL
888                          8890  430.0   10.0            Q   VXHFZN
203                          2040  148.0   10.0            T   NRLBSZ
538                          5390  350.0   10.0            J   WEUVDY
..                            ...    ...    ...          ...      ...
306                          3070  315.0   50.0            D   VFJBWF
670                          6710  191.0   50.0            A   QSURZT
559                          5600  395.0   50.0            T   CVSBMG
0                              10  192.0   50.0            F   NXEYEM
921  #Reza Dibaj, ST ID=101280076    NaN    NaN          NaN      NaN

[949 rows x 5 columns]

22 - . Sort the value Series in ascending order, showing the whole DataFrame.

In [37]:
myDF.sort_values(['id','range','value','machine_type','zip_code']) #Ascending is the standart 

id  range  value machine_type zip_code
921  #Reza Dibaj, ST ID=101280076    NaN    NaN          NaN      NaN
0                              10  192.0   50.0            F   NXEYEM
9                             100  347.0   30.0            K   RSVMXY
99                           1000  289.0   29.0            G   LCNMXV
100                          1010  343.0   21.0            U   WXEISY
..                            ...    ...    ...          ...      ...
950                          9500  137.0   10.0            W   JOHHVL
95                            960  184.0   13.0            F   MHRJTN
96                            970  486.0   36.0            W   XVYWMN
97                            980  133.0   15.0            T   AJLOVI
98                            990  201.0   21.0            Y   TYJAIQ

[949 rows x 5 columns]

23 - Sort the value Series in ascending order, showing the whole DataFrame, inplace

In [38]:
myDF.sort_values(['id','range','value','machine_type','zip_code'], inplace = True) #Ascending is the standart 

24 - Sort myDF DataFrame based on the range and value in ascending and descending order,
respectively. (range in ascending and value in descending order).

In [39]:
myDF.sort_values(['range','value'], ascending=[True,False])

id  range  value machine_type zip_code
504                          5050  100.0   21.0            S   KLYYQV
462                          4630  101.0   26.0            P   PBJHPM
798                          7990  101.0   20.0            E   QXAZJW
556                          5570  102.0   15.0            M   SSGQYR
751                          7520  103.0   44.0            Q   XOGVUH
..                            ...    ...    ...          ...      ...
163                          1640  499.0   13.0            M   JQQXBS
411                          4120  500.0   27.0            Q   NRNLPN
731                          7320  500.0   20.0            Z   JUKAMV
423                          4240  500.0   17.0            Q   IYUYPO
921  #Reza Dibaj, ST ID=101280076    NaN    NaN          NaN      NaN

[949 rows x 5 columns]

25 - Display those rows of myDF that their range is between 250 and 350.

In [40]:
myDF.loc[myDF.range.between(250,350)]

id  range  value machine_type zip_code
9     100  347.0   30.0            K   RSVMXY
99   1000  289.0   29.0            G   LCNMXV
100  1010  343.0   21.0            U   WXEISY
102  1030  331.0   26.0            Q   LQOEQI
105  1060  256.0   26.0            O   GFCGWN
..    ...    ...    ...          ...      ...
923  9230  276.0   30.0            C   CYADRG
930  9300  344.0   23.0            S   YRWLCJ
932  9320  302.0   30.0            C   MZEFTD
933  9330  258.0   14.0            P   MCWQKU
947  9470  316.0   46.0            L   SHBAUD

[204 rows x 5 columns]

26 - Display those rows of myDF that their range is between 250 and 350 in an ascending sorted
format.

In [41]:
myDF.loc[myDF.range.between(250,350)].sort_values(['range']) #Ascending is the standart 

id  range  value machine_type zip_code
57    580  250.0   19.0            K   EFXWGS
262  2630  250.0   12.0            O   ZZIXOA
811  8120  251.0   49.0            D   QOWNHD
307  3080  251.0   26.0            Z   YCKPXV
276  2770  252.0   38.0            J   SKKOYK
..    ...    ...    ...          ...      ...
645  6460  350.0   30.0            Q   LVDEAS
738  7390  350.0   24.0            X      NaN
538  5390  350.0   10.0            J   WEUVDY
833  8340  350.0   46.0            K   NCUWLM
382  3830  350.0   14.0            M   FOIOWR

[204 rows x 5 columns]

27 - Display only the id and value columns of those rows of myDF that their range is between 250 and
350.

In [42]:
myDF.loc[myDF.range.between(250,350), ['id','value']]

id  value
9     100   30.0
99   1000   29.0
100  1010   21.0
102  1030   26.0
105  1060   26.0
..    ...    ...
923  9230   30.0
930  9300   23.0
932  9320   30.0
933  9330   14.0
947  9470   46.0

[204 rows x 2 columns]

28 - Display only the id, value and machine_type columns of the of those rows of myDF that their
range is between 250 and 350 and their ‘machine_type’ is equal to ‘H’.

In [43]:
myDF.loc[(myDF.range.between(250,350)) & (myDF['machine_type'] == 'H') ,['id','value','machine_type']]

id  value machine_type
260  2610   50.0            H
302  3030   14.0            H
438  4390   11.0            H
445  4460   32.0            H
493  4940   16.0            H
525  5260   32.0            H
611  6120   11.0            H
620  6210   47.0            H

29 - 9. Display those rows of myDF that their ‘machine_type’ is equal to ‘H’ or ‘R’ or ‘X’. (entire
DataFrame)

In [44]:
myDF[myDF['machine_type'].isin(['H','R','X'])]

id  range  value machine_type zip_code
103  1040  156.0   44.0            H   JCLUXM
107  1080  163.0   35.0            X   RWZLSL
118  1190  441.0   42.0            X   VEJKRT
121  1220  170.0   14.0            H   UPUXVE
123  1240  415.0   32.0            H   QKMJLO
..    ...    ...    ...          ...      ...
866  8670  321.0   14.0            R   VBMYXU
871  8720  104.0   49.0            H   AGKGDY
891  8920  170.0   46.0            H   SBQKUZ
895  8960  333.0   43.0            R   UPOVQP
920  9210  446.0   27.0            H   WQCBIF

[101 rows x 5 columns]

30 - Show the myDF columns’ datatype. Display (select) only the numerical columns

In [45]:
myDF.dtypes

id               object
range           float64
value           float64
machine_type     object
zip_code         object
dtype: object

In [47]:
myDF.select_dtypes('float64')

range  value
921    NaN    NaN
0    192.0   50.0
9    347.0   30.0
99   289.0   29.0
100  343.0   21.0
..     ...    ...
950  137.0   10.0
95   184.0   13.0
96   486.0   36.0
97   133.0   15.0
98   201.0   21.0

[949 rows x 2 columns]